import type { CSSProperties } from "react";

/** Co-located styles for the skill ContextTab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8, flexWrap: "wrap" } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  repoPicker: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  filterBox: { marginLeft: "auto", width: 220 } satisfies CSSProperties,
  caption: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.5 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  rowDragging: { opacity: 0.5, border: "1px dashed var(--accent)" } satisfies CSSProperties,
  handle: {
    cursor: "grab",
    color: "var(--text-muted)",
    fontSize: 15,
    lineHeight: 1,
    userSelect: "none",
    width: 16,
    textAlign: "center",
  } satisfies CSSProperties,
  handlePlaceholder: { width: 16 } satisfies CSSProperties,
  orderBtns: { display: "flex", alignItems: "center", gap: 0 } satisfies CSSProperties,
  name: { fontSize: 13.5, color: "var(--text-primary)" } satisfies CSSProperties,
  path: {
    fontSize: 12,
    color: "var(--text-muted)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowEnd: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  noMatches: { fontSize: 13, color: "var(--text-muted)", padding: "20px 4px" } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  serializeSection: { marginTop: 28 } satisfies CSSProperties,
  serializeTitle: { fontSize: 14, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  serializeHint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 10, lineHeight: 1.5 } satisfies CSSProperties,
  serializeCard: { padding: "14px 16px" } satisfies CSSProperties,
  serializePre: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  drawerMeta: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16 } satisfies CSSProperties,
  drawerBody: { fontSize: 13.5 } satisfies CSSProperties,
} as const;
