import type { CSSProperties } from "react";

export const s = {
  page: {
    height: "calc(100vh - 52px)",
    display: "flex",
    flexDirection: "column",
    padding: "28px 32px 24px",
  } satisfies CSSProperties,
  inner: {
    width: "100%",
    maxWidth: 1080,
    margin: "0 auto",
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  heading: {
    margin: 0,
    fontSize: 22,
    fontWeight: 650,
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "baseline",
    gap: 6,
  } satisfies CSSProperties,
  headingRepo: {
    color: "var(--accent)",
    fontSize: 21,
  } satisfies CSSProperties,
  subtitle: {
    marginTop: 6,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  /* Master-detail: bordered container, left file list + right document pane. */
  layout: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  left: {
    width: 280,
    minWidth: 240,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
  } satisfies CSSProperties,
  leftHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "12px 12px 8px 16px",
  } satisfies CSSProperties,
  caption: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  fileList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    listStyle: "none",
    margin: 0,
    padding: "0 8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  fileBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    borderRadius: 7,
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  fileBtnSelected: {
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  fileName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    marginTop: 8,
  } satisfies CSSProperties,
  centered: {
    display: "grid",
    placeItems: "center",
    minHeight: "60vh",
  } satisfies CSSProperties,
} as const;
