import type { CSSProperties } from "react";

/** Co-located styles for the EvalsTab (mirrors ContextTab / SkillsTab). */
export const s = {
  wrap: { maxWidth: 860, display: "flex", flexDirection: "column", gap: 28 } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  dashboardLink: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--accent)",
    textDecoration: "none",
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: -6,
    marginBottom: 14,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  cards: { display: "flex", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  batchLine: {
    marginTop: 12,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  casesHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  headerActions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  progress: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    marginBottom: 12,
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    fontSize: 13,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  confirm: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    marginBottom: 12,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 13,
    color: "var(--text-primary)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
} as const;
